# Generated by Django 2.1.3 on 2018-11-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_recruit_shoot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='텍스트')),
                ('link', models.URLField(verbose_name='링크')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='콘텐츠')),
                ('recruit', models.ForeignKey(on_delete='공고', related_name='materials', to='mail.Recruit')),
            ],
        ),
        migrations.AddField(
            model_name='recruit',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='mail.Category'),
            preserve_default=False,
        ),
    ]
