# Generated by Django 2.1.3 on 2018-11-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20181114_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='img',
            field=models.CharField(default=0, max_length=255, verbose_name='이미지'),
            preserve_default=False,
        ),
    ]
