# Generated by Django 2.1.3 on 2018-11-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_recruit_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='detail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='특이사항'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='이미지'),
        ),
    ]
