# Generated by Django 2.1.3 on 2018-11-14 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_recruit_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruits', to='mail.Category'),
        ),
    ]
