# Generated by Django 2.1.3 on 2018-11-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_auto_20181114_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='코멘트'),
        ),
    ]
