# Generated by Django 2.1.3 on 2018-11-14 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_recruit_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='duedate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='마감일'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='place',
            field=models.CharField(default='서울', max_length=255, verbose_name='근무지'),
        ),
    ]
