# Generated by Django 2.1.3 on 2018-11-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_auto_20181114_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='_link',
            field=models.TextField(blank=True, null=True, verbose_name='참고자료 링크'),
        ),
        migrations.AddField(
            model_name='recruit',
            name='_materials',
            field=models.TextField(blank=True, null=True, verbose_name='참고자료'),
        ),
    ]
