# Generated by Django 2.1.3 on 2018-11-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_auto_20181114_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='img',
            field=models.URLField(blank=True, null=True, verbose_name='이미지'),
        ),
    ]
