# Generated by Django 2.1.3 on 2018-11-18 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0013_auto_20181118_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='로고'),
            preserve_default=False,
        ),
    ]
