# Generated by Django 2.1.3 on 2018-11-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0016_remove_recruit__link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='_materials',
        ),
    ]
