# Generated by Django 2.1.3 on 2018-11-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0017_remove_recruit__materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='_materials',
            field=models.TextField(blank=True, null=True, verbose_name='참고자료'),
        ),
    ]
